product_app_homepage:
    path:     /
    defaults: { _controller: ProductAppBundle:Default:index }

product_app_add_price:
    path: /price/new
    defaults: { _controller: ProductAppBundle:Price:add }
