services:
    product_domain.add_price.command_handler:
        class: Product\Domain\AddPrice\AddPriceCommandHandler
        lazy:  true
        arguments:
            - '@product_infrastructure.repository'

    product_infrastructure.repository:
        alias: product_infrastructure.repository.doctrine

    product_infrastructure.repository.doctrine:
        class: Product\Infrastructure\Doctrine\Repository\ProductRepository
        public: false
        factory:
            - '@doctrine.orm.default_entity_manager'
            - getRepository
        arguments:
            - Product\Domain\Product

    product_infrastructure.repository.in_memory:
        class: Product\Infrastructure\InMemory\Repository\ProductRepository
        public: false
